### ISSUE TITLE
如何使用这个机器人来学？

### ISSUE THREAD

**Issue by noway2014** [bifu123/qqbot2#1]
谢谢……

**Comment by bifu123** [comment]
加QQ群：478907529




------------------ 原始邮件 ------------------
发件人: "noway2014"<notifications@github.com>; 
发送时间: 2019年5月15日(星期三) 下午3:40
收件人: "bifu123/qqbot2"<qqbot2@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [bifu123/qqbot2] 如何使用这个机器人来学？ (#1)




Closed #1.
